plugins {
    id 'com.android.application'
    id 'com.chaquo.python'
}

android {
    namespace 'br.com.oceanolivre.kraken'
    compileSdk 34

    defaultConfig {
        applicationId "br.com.oceanolivre.kraken"
        minSdk 24
        targetSdk 34
        versionCode 37
        versionName "1.8.5"

        ndk {
            abiFilters "arm64-v8a"
        }
    }

    buildTypes {
        debug {
            debuggable true
        }
        release {
            minifyEnabled false
            signingConfig signingConfigs.debug
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    buildFeatures {
        buildConfig true
    }
}

chaquopy {
    defaultConfig {
        version = "3.12"
        buildPython("C:/Users/Usuario/AppData/Local/Programs/Python/Python312/python.exe")
        pip {
            install "flask"
            install "werkzeug"
            install "flask-socketio"
            install "simple-websocket"
            install "qrcode"
            install "pynacl"
        }
    }
}

dependencies {
    implementation 'androidx.core:core:1.13.1'
    implementation 'androidx.webkit:webkit:1.11.0'
}
